controllers:
    resource: ../src/Controller/
    type: attribute

auth:
    path: /auth
    methods: ['POST']

auth_user:
    path: /auth/user
    methods: ['GET']
    controller: App\Controller\UserAuthController.php
    